package com.fiddovea.fiddovea.dto.response;

public enum ResponseMessage {
    WELCOME_BACK,
    REGISTRATION_SUCCESSFUL,
    PENDING_BUSINESS_DETAIL_VERIFICATION,
    PRODUCT_ADDED_TO_CART,
    PRODUCT_ADDED_TO_WISH_LIST,
    PRODUCT_ADDED,
    ITEM_REMOVED,
    PRODUCT_DELETED_SUCCESSFULLY,
    CHAT_NOT_FIND,
    MESSAGE_SENT,


    IF_YOUR_EMAIL_IS_REGISTERED_YOU_WILL_GET_A_MESSAGE_FROM_US;
}
