package com.fiddovea.fiddovea.dto.response;

public enum ResponseMessage {
    WELCOME_BACK,
    REGISTRATION_SUCCESSFUL,
    PENDING_BUSINESS_DETAIL_VERIFICATION,
    PROFILE_UPDATE_SUCCESSFUL,
    PRODUCT_ADDED_TO_CART,
    PRODUCT_ADDED_TO_WISH_LIST,
    PRODUCT_ADDED,
    ITEM_REMOVED,
    NO_ORDER_FOUND,
    NOTIFICATION_SENT_SUCCESSFULLY,
    PRODUCT_DELETED_SUCCESSFULLY,
<<<<<<< HEAD
    VERIFICATION_SUCCESSFUL,
    CHAT_NOT_FIND,
    PLEASE_CHECK_YOUR_MAIL_FOR_VERIFICATION_CODE,
    REVIEW_SUCCESSFUL_THANKS_FOR_YOUR_TIME,
    MESSAGE_SENT,
=======
    YOU_ADD_THE_PRODUCT_TO_YOUR_WISHLIST,
    YOUR_PRODUCT_HAS_BEEN_ADDED_SUCCESSFULLY,
>>>>>>> 54383a5e8f93c03fa27fdfbce2a73b958b0f7afb
    IF_YOUR_EMAIL_IS_REGISTERED_YOU_WILL_GET_A_MESSAGE_FROM_US
}
