package com.fiddovea.fiddovea.dto.response;

public enum ResponseMessage {
    WELCOME_BACK,
    REGISTRATION_SUCCESSFUL,
    PENDING_BUSINESS_DETAIL_VERIFICATION,
    PROFILE_UPDATE_SUCCESSFUL,
    PRODUCT_ADDED_TO_CART,
    PRODUCT_ADDED_TO_WISH_LIST,
    PRODUCT_ADDED,
    ITEM_REMOVED,
    NO_ORDER_FOUND,
    NOTIFICATION_SENT_SUCCESSFULLY,
    PRODUCT_DELETED_SUCCESSFULLY,
    YOU_ADD_THE_PRODUCT_TO_YOUR_WISHLIST,
    YOUR_PRODUCT_HAS_BEEN_ADDED_SUCCESSFULLY,
    IF_YOUR_EMAIL_IS_REGISTERED_YOU_WILL_GET_A_MESSAGE_FROM_US
}
